Fix for py35 metaclass error
The py35 unit tests are not able to run because of the following
metaclass related error:

=========================
Failures during discovery
=========================
--- import errors ---
Failed to import test module: networking_vpp.tests.unit.test_vppforwarder
Traceback (most recent call last):
  File "/opt/stack/tmp/networking-vpp/.tox/py35/lib/python3.5/site-packages/unittest2/loader.py", line 456, in _find_test_path
    module = self._get_module_from_name(name)
  File "/opt/stack/tmp/networking-vpp/.tox/py35/lib/python3.5/site-packages/unittest2/loader.py", line 395, in _get_module_from_name
    __import__(name)
  File "/opt/stack/tmp/networking-vpp/networking_vpp/tests/unit/test_vppforwarder.py", line 26, in <module>
    from networking_vpp.agent import server
  File "/opt/stack/tmp/networking-vpp/networking_vpp/agent/server.py", line 60, in <module>
    from networking_vpp.utils import file_monitor
  File "/opt/stack/tmp/networking-vpp/networking_vpp/utils/file_monitor.py", line 20, in <module>
    import pyinotify
  File "/opt/stack/tmp/networking-vpp/.tox/py35/lib/python3.5/site-packages/pyinotify.py", line 1405, in <module>
    class ThreadedNotifier(threading.Thread, Notifier):
TypeError: metaclass conflict: the metaclass of a derived class must be a (non-strict) subclass of the metaclasses of all its bases

This was happening due to the threading module being mocked. The patch fixes
the problem.

Change-Id: Idaf0431165b2e9ce04cf8e275b976d31ea996b30